name: gym-dev

services:
  gym-workload-server:
    container_name: gym-workload-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - gym-dev-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-dev-network:
    external: true
