spring:
  application:
    name: gym-workload-service
  config:
    import: "configserver:http://gym-config-service:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: gym-workload-consumer-group

server:
  port: 8082
